# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: 言語処理100本ノック 2025
author: 
copyright: |
  2012-2025 by 岡崎 直観 (Naoaki Okazaki), クリエイティブ・コモンズ 表示 4.0 国際 (CC BY 4.0)"
exclude_patterns: [tools, data, _build, material, pdf, README.md, .DS_Store, "**.ipynb_checkpoints"]

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: 'off'

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

parse:
  myst_html_meta:
    twitter\:card": "summary"
    twitter\:site: "@chokkanorg"
    twitter\:title: "言語処理100本ノック"
    twitter\:description: "言語処理100本ノックは、実用的でワクワクするような課題に取り組みながら、自然言語処理、大規模言語モデル、プログラミング、研究のスキルを楽しく習得することを目指した問題集です。"
    twitter\:image: "https://chokkan.github.io/mlnote/_static/mlnote.png"
# Add a bibtex file so that we can create citations
# bibtex_bibfiles:
#  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/nlp100/2025  # Online location of your book
  #path_to_book: # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  baseurl: "https://nlp100.github.io/"
  use_issues_button: true
  use_repository_button: true
  extra_footer: |                    # Will be displayed underneath the footer.
    <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="クリエイティブ・コモンズ・ライセンス" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/80x15.png" /></a>

# Launch button settings
launch_buttons:
  notebook_interface        : "jupyterlab" # The interface interactive links will activate ["classic", "jupyterlab"]
  colab_url                 : "https://colab.research.google.com" # The URL of Google Colab (https://colab.research.google.com)
